home:
    path: /
    controller: App\Controller\HomeController::index

z5600:
    path: /z5600
    controller: App\Controller\Z5600Controller::index

z5600_new:
    path: /new
    controller: App\Controller\Z5600Controller::new

z5600_show:
    path: /{id}
    controller: App\Controller\Z5600Controller::show

z5600_edit:
    path: /{id}/edit
    controller: App\Controller\Z5600Controller::edit

z5600_delete:
    path: /{id}
    controller: App\Controller\Z5600Controller::delete

