home:
    path: /
    controller: App\Controller\HomeController::index

rerng:
    path: /rerng
    controller: App\Controller\RERNGController::index

rerng_new:
    path: /new
    controller: App\Controller\RERNGController::new

rerng_show:
    path: /{id}
    controller: App\Controller\RERNGController::show

rerng_edit:
    path: /{id}/edit
    controller: App\Controller\RERNGController::edit

rerng_delete:
    path: /{id}
    controller: App\Controller\RERNGController::delete

z5600:
    path: /z5600
    controller: App\Controller\Z5600Controller::index

z5600_new:
    path: /new
    controller: App\Controller\Z5600Controller::new

z5600_show:
    path: /{id}
    controller: App\Controller\Z5600Controller::show

z5600_edit:
    path: /{id}/edit
    controller: App\Controller\Z5600Controller::edit

z5600_delete:
    path: /{id}
    controller: App\Controller\Z5600Controller::delete



users:
    path: /users
    controller: App\Controller\UsersController::index

users_edit:
    path: /{id}/edit
    controller: App\Controller\UsersController::edit

users_delete:
    path: /{id}
    controller: App\Controller\UsersController::delete





dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

