vich_uploader:
  db_driver: orm
  
  
  mappings:
    article_images:
      uri_prefix: /uploads/images
      upload_destination: '%kernel.project_dir%/public%app.path.person_images%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer