vich_uploader:
    db_driver: orm
  
  
    mappings:
        article_images:
            uri_prefix: /public
            upload_destination: '%kernel.project_dir%/public'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        realisation_images:
            uri_prefix: /public
            upload_destination: '%kernel.project_dir%/public'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        avatar_images:
            uri_prefix: /public
            upload_destination: '%kernel.project_dir%/public'
            namer: Vich\UploaderBundle\Naming\UniqidNamer