vich_uploader:
  db_driver: orm
  
  
  mappings:
    article_images:
      uri_prefix: /public/uploads/images
      upload_destination: '%kernel.project_dir%/public/uploads/images'
      namer: Vich\UploaderBundle\Naming\UniqidNamer